package com.runing.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;
import java.util.List;

public class RuningActive {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_active.active_id
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    private String activeId;

    public String getActiveUserid() {
        return activeUserid;
    }

    public void setActiveUserid(String activeUserid) {
        this.activeUserid = activeUserid;
    }

    //    活动创建人
private String  activeUserid;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_active.active_name
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    private String activeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_active.active_info
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    private String activeInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_active.active_address
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    private String activeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_active.active_predictnum
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    private Integer activePredictnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_active.active_yetnum
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    private Integer activeYetnum;

    public Integer getActiveIsdel() {
        return activeIsdel;
    }

    public void setActiveIsdel(Integer activeIsdel) {
        this.activeIsdel = activeIsdel;
    }

    //    是否删除
    private Integer activeIsdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_active.active_createtime
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
    private Date activeCreatetime;
//   活动开始时间
@JsonFormat(pattern = "yyyy-MM-dd HH:mm", timezone = "GMT+08:00")
    private Date  activeStarttime;

    public Date getActiveStarttime() {
        return activeStarttime;
    }

    public void setActiveStarttime(Date activeStarttime) {
        this.activeStarttime = activeStarttime;
    }

    public Date getActiveEndtime() {
        return activeEndtime;
    }

    public void setActiveEndtime(Date activeEndtime) {
        this.activeEndtime = activeEndtime;
    }

    //   活动结束时间
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm", timezone = "GMT+08:00")
    private Date  activeEndtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_active.active_updatetime
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
    private Date activeUpdatetime;
    // 版本信息
    /**
     * 版本号
     */
    private String version;

    // 分页数据
    /**
     * 当前页数(如果不进行分页，该条数据默认为-1)
     */
    private Integer pagenumber;

    /**
     * 每页的数据量
     */
    private Integer pagesize;

    // 操作数据

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public Integer getPagenumber() {
        return pagenumber;
    }

    public void setPagenumber(Integer pagenumber) {
        this.pagenumber = pagenumber;
    }

    public Integer getPagesize() {
        return pagesize;
    }

    public void setPagesize(Integer pagesize) {
        this.pagesize = pagesize;
    }

    public List<String> getUuidlist() {
        return uuidlist;
    }

    public void setUuidlist(List<String> uuidlist) {
        this.uuidlist = uuidlist;
    }

    /**
     * 根据uuidlist删除信息时使用
     */
    private List<String> uuidlist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_active.active_id
     *
     * @return the value of runing_active.active_id
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public String getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_active.active_id
     *
     * @param activeId the value for runing_active.active_id
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public void setActiveId(String activeId) {
        this.activeId = activeId == null ? null : activeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_active.active_name
     *
     * @return the value of runing_active.active_name
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public String getActiveName() {
        return activeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_active.active_name
     *
     * @param activeName the value for runing_active.active_name
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public void setActiveName(String activeName) {
        this.activeName = activeName == null ? null : activeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_active.active_info
     *
     * @return the value of runing_active.active_info
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public String getActiveInfo() {
        return activeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_active.active_info
     *
     * @param activeInfo the value for runing_active.active_info
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public void setActiveInfo(String activeInfo) {
        this.activeInfo = activeInfo == null ? null : activeInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_active.active_address
     *
     * @return the value of runing_active.active_address
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public String getActiveAddress() {
        return activeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_active.active_address
     *
     * @param activeAddress the value for runing_active.active_address
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public void setActiveAddress(String activeAddress) {
        this.activeAddress = activeAddress == null ? null : activeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_active.active_predictnum
     *
     * @return the value of runing_active.active_predictnum
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public Integer getActivePredictnum() {
        return activePredictnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_active.active_predictnum
     *
     * @param activePredictnum the value for runing_active.active_predictnum
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public void setActivePredictnum(Integer activePredictnum) {
        this.activePredictnum = activePredictnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_active.active_yetnum
     *
     * @return the value of runing_active.active_yetnum
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public Integer getActiveYetnum() {
        return activeYetnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_active.active_yetnum
     *
     * @param activeYetnum the value for runing_active.active_yetnum
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public void setActiveYetnum(Integer activeYetnum) {
        this.activeYetnum = activeYetnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_active.active_createtime
     *
     * @return the value of runing_active.active_createtime
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public Date getActiveCreatetime() {
        return activeCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_active.active_createtime
     *
     * @param activeCreatetime the value for runing_active.active_createtime
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public void setActiveCreatetime(Date activeCreatetime) {
        this.activeCreatetime = activeCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_active.active_updatetime
     *
     * @return the value of runing_active.active_updatetime
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public Date getActiveUpdatetime() {
        return activeUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_active.active_updatetime
     *
     * @param activeUpdatetime the value for runing_active.active_updatetime
     *
     * @mbg.generated Mon Apr 01 14:36:25 CST 2019
     */
    public void setActiveUpdatetime(Date activeUpdatetime) {
        this.activeUpdatetime = activeUpdatetime;
    }
}