package com.runing.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;
import java.util.List;

public class RuningApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_apply.apply_id
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    private String applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_apply.apply_userid
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    private String applyUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_apply.apply_activeid
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    private String applyActiveid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_apply.apply_createtime
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
    private Date applyCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_apply.apply_updatetime
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
    private Date applyUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runing_apply.apply_isdel
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    private Integer applyIsdel;
    // 版本信息
    /**
     * 版本号
     */
    private String version;

    // 分页数据
    /**
     * 当前页数(如果不进行分页，该条数据默认为-1)
     */
    private Integer pagenumber;

    /**
     * 每页的数据量
     */
    private Integer pagesize;

    // 操作数据

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public Integer getPagenumber() {
        return pagenumber;
    }

    public void setPagenumber(Integer pagenumber) {
        this.pagenumber = pagenumber;
    }

    public Integer getPagesize() {
        return pagesize;
    }

    public void setPagesize(Integer pagesize) {
        this.pagesize = pagesize;
    }

    public List<String> getUuidlist() {
        return uuidlist;
    }

    public void setUuidlist(List<String> uuidlist) {
        this.uuidlist = uuidlist;
    }

    /**
     * 根据uuidlist删除信息时使用
     */
    private List<String> uuidlist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_apply.apply_id
     *
     * @return the value of runing_apply.apply_id
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_apply.apply_id
     *
     * @param applyId the value for runing_apply.apply_id
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_apply.apply_userid
     *
     * @return the value of runing_apply.apply_userid
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public String getApplyUserid() {
        return applyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_apply.apply_userid
     *
     * @param applyUserid the value for runing_apply.apply_userid
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public void setApplyUserid(String applyUserid) {
        this.applyUserid = applyUserid == null ? null : applyUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_apply.apply_activeid
     *
     * @return the value of runing_apply.apply_activeid
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public String getApplyActiveid() {
        return applyActiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_apply.apply_activeid
     *
     * @param applyActiveid the value for runing_apply.apply_activeid
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public void setApplyActiveid(String applyActiveid) {
        this.applyActiveid = applyActiveid == null ? null : applyActiveid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_apply.apply_createtime
     *
     * @return the value of runing_apply.apply_createtime
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public Date getApplyCreatetime() {
        return applyCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_apply.apply_createtime
     *
     * @param applyCreatetime the value for runing_apply.apply_createtime
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public void setApplyCreatetime(Date applyCreatetime) {
        this.applyCreatetime = applyCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_apply.apply_updatetime
     *
     * @return the value of runing_apply.apply_updatetime
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public Date getApplyUpdatetime() {
        return applyUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_apply.apply_updatetime
     *
     * @param applyUpdatetime the value for runing_apply.apply_updatetime
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public void setApplyUpdatetime(Date applyUpdatetime) {
        this.applyUpdatetime = applyUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runing_apply.apply_isdel
     *
     * @return the value of runing_apply.apply_isdel
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public Integer getApplyIsdel() {
        return applyIsdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runing_apply.apply_isdel
     *
     * @param applyIsdel the value for runing_apply.apply_isdel
     *
     * @mbg.generated Mon Apr 01 14:36:01 CST 2019
     */
    public void setApplyIsdel(Integer applyIsdel) {
        this.applyIsdel = applyIsdel;
    }
}